version: 1
name: "Mobile Build Workflow"
on:
  push:
    branches:
      - main
      - master

jobs:
  test_connection:
    name: "Validate GitHub Hook"
    steps:
      - name: "Say Hello"
        run: echo "TurtleCI successfully connected to GitHub!"
